### PR TITLE
Text adjustments to better match the size of the buttons

### PR DESCRIPTION
**Pull request by Felix14-v2**
Although, even this is not enough. 
image

I think this is the final translation for the new version.

### CODE REVIEW

**Comment by DeathsGun** [comment]
I can also make the sorting button bigger

**Comment by Felix14-v2** [comment]
That would be nice. 
Even better, if the size was adjusted to the length of the text.

**Comment by DeathsGun** [comment]
I have adjusted the button size then this shouldn’t be necessary or not?

**Comment by Felix14-v2** [comment]
I think now the text will not go beyond the borders of the buttons.

**Pull request merged**
